framework:
    annotations: false
    secret: '%env(KERNEL_SECRET)%'
    router:
        resource: '%kernel.project_dir%/config/routes.yaml'
        type: yaml

    # Session configuration
    session:
        enabled: true
        handler_id: 'session.handler.pdo' # Use the PDO session handler
        cookie_secure: auto              # Automatically secure cookies in HTTPS
        cookie_samesite: lax             # Prevent cross-site cookie sharing
        save_path: '%env(resolve:DATABASE_URL)%' # Use database for session storage
