

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
framework:
    router:
        resource: '%kernel.project_dir%/config/routes.yaml'
        type: yaml
    session:
        cookie_samesite: 'none'  # Attention à la casse : "none" (pas "None")



    
