# framework:
#     annotations: false
#     secret: '%env(KERNEL_SECRET)%'
#     router:
#         resource: '%kernel.project_dir%/config/routes.yaml'
#         type: yaml

#     session:
#         enabled: true
#         handler_id: null
#         cookie_secure: auto              # Automatically secure cookies in HTTPS
#         cookie_samesite: lax             # Prevent cross-site cookie sharing
#         save_path: '%kernel.project_dir%/var/sessions'
#     # session:
#     #     enabled: true
#     #     handler_id: 'session.handler.pdo' # Use the PDO session handler
#     #     cookie_secure: auto              # Automatically secure cookies in HTTPS
#     #     cookie_samesite: lax             # Prevent cross-site cookie sharing
#     #     save_path: '%env(resolve:DATABASE_URL)%' 









framework:
    translator:
        enabled: false
    secret: '%env(KERNEL_SECRET)%'
    router:
        resource: '%kernel.project_dir%/config/routes.yaml'
        type: yaml

    session:
        enabled: true
        handler_id: 'session.handler.pdo' # Use the PDO session handler
        cookie_secure: auto              # Automatically secure cookies in HTTPS
        cookie_httponly: true            # Make session cookies inaccessible via JavaScript
        cookie_samesite: strict          # Prevent cross-site request issues
