

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
framework:
    router:
        resource: '%kernel.project_dir%/config/routes.yaml'
        type: yaml
    session:
        cookie_secure: auto # ou true si vous êtes en HTTPS uniquement
        cookie_samesite: None



    
