# framework:
#     annotations: false
#     secret: '%env(KERNEL_SECRET)%'
#     router:
#         resource: '%kernel.project_dir%/config/routes.yaml'
#         type: yaml

#     # Session configuration
#     session:
#         enabled: true
#         handler_id: null
#         cookie_secure: auto              # Automatically secure cookies in HTTPS
#         cookie_samesite: lax             # Prevent cross-site cookie sharing
#         save_path: '%kernel.project_dir%/var/sessions'








framework:
    annotations: false
    secret: '%env(KERNEL_SECRET)%'
    router:
        resource: '%kernel.project_dir%/config/routes.yaml'
        type: yaml

    session:
        enabled: true
        handler_id: 'redis_session_handler'
        cookie_secure: auto # Utilise HTTPS si disponible
        cookie_samesite: lax # Compatible avec les requêtes inter-domaines
        cookie_lifetime: 0 # Le cookie expire à la fin de la session
