# framework:
#     secret: '%env(KERNEL_SECRET)%'
#     router:
#         resource: '%kernel.project_dir%/config/routes.yaml'
#         type: yaml
#     session:
#         enabled: true # Active les sessions
#         handler_id: ~ # Utilise le gestionnaire de sessions PHP par défaut
#         cookie_secure: auto # "auto" pour HTTPS, "false" pour HTTP en local
#         cookie_samesite: lax # Réduit les risques de CSRF
#     csrf_protection:
#         enabled: true # Active la protection CSRF

 


# framework:
#     annotations: false
#     secret: '%env(KERNEL_SECRET)%'
#     router:
#         resource: '%kernel.project_dir%/config/routes.yaml'
#         type: yaml
#     # session:
#     #     enabled: true
#     #     handler_id: ~  # Utilise le gestionnaire de session natif de PHP
#     #     cookie_secure: false  # Assurez-vous que c'est désactivé en développement si vous utilisez HTTP
#     #     cookie_samesite: lax  # Réduit les risques de CSRF lors des redirections
#     # csrf_protection:
#     #     enabled: true
#     session:
#         enabled: true
#         handler_id: null  # Utiliser le gestionnaire de session natif de PHP
#         cookie_secure: auto  # Devrait être "auto" pour gérer HTTP/HTTPS automatiquement
#         cookie_samesite: lax
#     csrf_protection:
#         enabled: true

#         # config/packages/messenger.yaml
#     messenger:
#         transports:
#             async: '%env(MESSENGER_TRANSPORT_DSN)%'
#         routing:
#             'App\Message\SendEmailMessage': async














# framework:
#     annotations: false
#     secret: '%env(KERNEL_SECRET)%'
#     router:
#         resource: '%kernel.project_dir%/config/routes.yaml'
#         type: yaml

#     # Activer les sessions pour gérer les jetons CSRF
#     session:
#         enabled: true
#         handler_id: null  # Utiliser le gestionnaire natif de PHP
#         cookie_secure: auto  # Gère automatiquement HTTP ou HTTPS
#         cookie_samesite: lax  # Limite les risques de CSRF

#     # Protection CSRF activée
#     csrf_protection:
#         enabled: true

#     messenger:
#         transports:
#             async: '%env(MESSENGER_TRANSPORT_DSN)%'
#         routing:
#             'App\Message\SendEmailMessage': async













framework:
    secret: '%env(KERNEL_SECRET)%'

    # Configuration des routes
    router:
        resource: '%kernel.project_dir%/config/routes.yaml'
        type: yaml

    # Sessions
    session:
        enabled: true
        handler_id: null  # Utiliser le gestionnaire natif de PHP
        cookie_secure: true  # Forcer HTTPS (assurez-vous que votre application est sur HTTPS)
        cookie_samesite: lax  # Limiter les risques de CSRF
        cookie_lifetime: 3600  # Durée de vie des cookies en secondes (1 heure)
        save_path: '%kernel.project_dir%/var/sessions'  # Chemin de stockage des sessions

    # Protection CSRF
    csrf_protection:
        enabled: true

    # Gérer les trusted proxies pour Railway ou tout proxy HTTPS
    trusted_proxies: ['127.0.0.1', '::1', '%env(TRUSTED_PROXIES)%']
    trusted_headers:
        - X_FORWARDED_FOR
        - X_FORWARDED_HOST
        - X_FORWARDED_PROTO
        - X_FORWARDED_PORT
        - X_FORWARDED_PREFIX

    # Validation et normalisation des données
    validation: { enable_annotations: true }

    # Méthodes HTTP supplémentaires autorisées (PATCH, DELETE, etc.)
    http_method_override: true

    # Gestion des messages asynchrones (messenger)
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Message\SendEmailMessage': async
