# security:
#     providers:
#         in_memory:
#             memory:
#                 users:
#                     JYD:
#                         password: '$2y$13$1/VbnsiiACDZ7QMBSGHrIewQ0pIm1zZBWo6Iq.ouxv0Vfz7fF7N3O'
#                         roles: ['ROLE_ADMIN']

#     password_hashers:
#         Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

#     firewalls:
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false

#         api:
#             pattern: ^/api/
#             stateless: true
#             security: false

#         main:
#             provider: in_memory
#             form_login:
#                 login_path: login
#                 check_path: login
#                 enable_csrf: true
#                 default_target_path: /admin
#             logout:
#                 path: /logout
#                 target: /login
#             # remember_me:
#             #     secret: '%env(APP_SECRET)%'
#             #     lifetime: 3600
#             #     path: /
#             #     secure: true

#     access_control:
#         - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/admin, roles: ROLE_ADMIN }











security:
    providers:
        in_memory:
            memory:
                users:
                    JYD:
                        password: '$2y$13$BWGq8qXaJGoFAaVrZt0l0efClIfKEIgdfKMjuccoYZjJ7qF4iTEa.'
                        roles: ['ROLE_ADMIN']

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api/
            stateless: true
            security: false

        main:
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: /admin
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
