version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Le port d'accès à votre application Symfony
    environment:
      APP_ENV: prod
      APP_SECRET: 123456789azertyuiop123456789
      DATABASE_URL: mysql://admin:abcdefgh@db:3306/database-1?serverVersion=8.0.32&charset=utf8mb4
      MAILER_DSN: smtp://jy.dellon@gmail.com:kora%%20xtrq%%20fzgk%%20iasj@smtp.gmail.com:587
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database-1
      MYSQL_USER: admin
      MYSQL_PASSWORD: abcdefgh
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  mailer:
    image: axllent/mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
