version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aeonix_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw
    environment:
      APP_ENV: dev
      APP_SECRET: 123456789azertyuiop123456789
      DATABASE_URL: "mysql://admin:abcdefgh@database-1.clis8kiwc2pt.eu-north-1.rds.amazonaws.com:3306/database-1?serverVersion=8.0.32&charset=utf8mb4"
      MAILER_DSN: "smtp://jy.dellon@gmail.com:kora%%20xtrq%%20fzgk%%20iasj@smtp.gmail.com:587"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database-1
      MYSQL_USER: admin
      MYSQL_PASSWORD: abcdefgh
    ports:
      - "3306:3306"
