version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Le port d'accès à votre application Symfony
    environment:
      APP_ENV: dev
      APP_SECRET: 123456789azertyuiop123456789
      DATABASE_URL: mysql://admin:abcdefgh@database-1.clis8kiwc2pt.eu-north-1.rds.amazonaws.com:3306/database-1?serverVersion=8.0.32&charset=utf8mb4
      MAILER_DSN: smtp://jy.dellon@gmail.com:kora%%20xtrq%%20fzgk%%20iasj@smtp.gmail.com:587
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: admin
      MYSQL_PASSWORD: abcdefgh
    ports:
      - "3307:3306"

  # Optionnel : phpMyAdmin pour gérer votre base de données facilement
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
