service: symfony-app

provider:
  name: aws
  region: us-east-1
  runtime: provided.al2  # Runtime personnalisé pour PHP via Bref
  memorySize: 1024
  timeout: 30

plugins:
  - ./vendor/bref/bref

functions:
  web:
    handler: public/index.php
    runtime: provided.al2  # Runtime pour PHP
    layers:
      - ${bref:layer.php-81-fpm}  # Layer PHP 8.1 pour Symfony
    events:
      - httpApi: '*'
