# service: symfony-app

# provider:
#   name: aws
#   runtime: provided.al2
#   region: us-east-1

# plugins:
#   - ./vendor/bref/bref

# functions:
#   web:
#     handler: public/index.php # Assurez-vous que index.php est dans le dossier public
#     layers:
#       - ${bref:layer.php-82} # Utilisation de PHP 8.2
#     events:
#       - httpApi:
#           path: /
#           method: ANY

# resources:
#   Resources:
#     MyApiGateway:
#       Type: AWS::ApiGatewayV2::Api
#       Properties:
#         Name: symfony-app-api
#         ProtocolType: HTTP
#         CorsConfiguration:
#           AllowOrigins:
#             - '*' # Autoriser toutes les origines (remplacez par votre domaine si nécessaire)
#           AllowMethods:
#             - GET
#             - POST
#             - PUT
#             - DELETE
#             - OPTIONS
#           AllowHeaders:
#             - Authorization
#             - Content-Type














service: symfony-app

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1

plugins:
  - ./vendor/bref/bref

functions:
  web:
    handler: public/index.php # Assurez-vous que index.php est dans le dossier public
    layers:
      - ${bref:layer.php-82} # Utilisation de PHP 8.2
    environment: # Variables d'environnement pour Symfony
      APP_ENV: dev
      APP_DEBUG: "1"
    events:
      - httpApi:
          path: /
          method: ANY

resources:
  Resources:
    MyApiGateway:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: symfony-app-api
        ProtocolType: HTTP
        CorsConfiguration:
          AllowOrigins:
            - '*' # Autoriser toutes les origines (remplacez par votre domaine si nécessaire)
          AllowMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          AllowHeaders:
            - Authorization
            - Content-Type
