

controllers:
    resource: '../src/Controller/'
    type: attribute






# config/routes.yaml

api_record_visit:
    path: /api/visit/{pageUrl}
    controller: App\Controller\PageVisitController::recordVisit
    methods: [POST, OPTIONS]
 
api_get_visits:
    path: /api/visit
    controller: App\Controller\PageVisitController::getVisits
    methods: [GET]

api_reset_visits:
    path: /api/visit
    controller: App\Controller\PageVisitController::resetVisits
    methods: [DELETE]






# Routes pour la gestion des prospects
api_contact:
    path: /api/contact
    controller: App\Controller\ProspectController::handleContact
    methods: POST

api_devis:
    path: /api/devis
    controller: App\Controller\ProspectController::handleDevis
    methods: POST

# api_prospects_list:
#     path: /api/prospects
#     controller: App\Controller\ProspectController::listProspects
#     methods: GET

# api_prospects_create:
#     path: /api/prospects
#     controller: App\Controller\ProspectController::createProspect
#     methods: POST

# api_prospect_update:
#     path: /api/prospect/{id}
#     controller: App\Controller\ProspectController::updateProspect
#     methods: PUT

# api_prospect_delete:
#     path: /api/prospect/{id}
#     controller: App\Controller\ProspectController::deleteProspect
#     methods: DELETE

# api_prospects_bulk_delete:
#     path: /api/prospects/delete
#     controller: App\Controller\ProspectController::deleteMultipleProspects
#     methods: POST

# Routes pour la gestion des visites
api_visits:
    path: /api/visit
    controller: App\Controller\VisitController::listVisits
    methods: GET

api_visit_reset:
    path: /api/visit/reset
    controller: App\Controller\VisitController::resetVisits
    methods: DELETE




prospect_index:
    path: /prospect
    controller: App\Controller\ProspectController::index
    methods: [GET]

# prospect_new:
#     path: /prospect/new
#     controller: App\Controller\ProspectController::create
#     methods: [GET, POST]

prospect_edit:
    path: /prospect/edit/{id}
    controller: App\Controller\ProspectController::edit
    methods: [GET, POST]

prospect_delete:
    path: /prospect/delete/{id}
    controller: App\Controller\ProspectController::delete
    methods: [POST]


# admin_page_visit_delete:
#     path: /admin/page-visits/{id}
#     controller: App\Controller\PageVisitController::delete
#     methods: [POST]

admin_routes:
    resource: ../src/Controller/Admin/
    type: attribute



delete_multiple_prospects:
    path: /delete-multiple
    controller: App\Controller\ProspectController::deleteMultiple
    methods: [POST]

send_emails:
    path: /send-emails
    controller: App\Controller\ProspectController::sendEmails
    methods: [POST]









# Route pour créer un prospect (GET et POST)
# admin_prospect_new:
#     path: /admin/prospects/new
#     controller: App\Controller\Admin\ProspectAdminController::new
#     methods: [GET, POST]

# Route pour afficher un prospect spécifique
# admin_prospect_show:
#     path: /admin/prospects/{id}
#     controller: App\Controller\Admin\ProspectAdminController::show
#     methods: [GET]

# Route pour modifier un prospect (GET et POST)
# admin_prospect_edit:
#     path: /admin/prospects/{id}/edit
#     controller: App\Controller\Admin\ProspectAdminController::edit
#     methods: [GET, POST]

# Route pour supprimer un prospect (POST uniquement)
# admin_prospect_delete:
#     path: /admin/prospects/{id}
#     controller: App\Controller\Admin\ProspectAdminController::delete
#     methods: [POST]



# admin_prospect_index:
#     path: /admin/prospects/
#     controller: App\Controller\Admin\ProspectAdminController::index
#     methods: [GET]

admin_prospects_post:
    path: /admin/prospects/send-mails
    controller: App\Controller\Admin\ProspectAdminController::handleProspects
    methods: [POST]

# get_prospects_emails:
#     path: /admin/prospects/get-emails
#     controller: App\Controller\Admin\ProspectAdminController::getProspectsEmails
#     methods: [POST]


send_prospect_mails:
    path: /admin/prospects/send-mails
    controller: App\Controller\YourControllerName::sendMails
    methods: [POST]



# admin_prospect_index2:
#     path: /
#     controller: App\Controller\Admin\ProspectAdminController::index2
#     methods: ['GET']



# api_prospects_bulk_delete:
#     path: /api/prospects/delete
#     controller: App\Controller\ProspectController::deleteMultipleProspects
#     methods: [POST]













api_prospects_list:
    path: /api/prospects
    controller: App\Controller\ProspectController::listProspects
    methods: GET

api_prospects_create:
    path: /api/prospects
    controller: App\Controller\ProspectController::createProspect
    methods: [POST]

api_prospect_update:
    path: /api/prospect/{id}
    controller: App\Controller\ProspectController::updateProspect
    methods: PUT

api_prospect_delete:
    path: /api/prospect/{id}
    controller: App\Controller\ProspectController::deleteProspect
    methods: [DELETE]







# admin_prospect_delete_multiple:
#     path: /admin/prospects/delete-multiple
#     controller: App\Controller\Admin\ProspectAdminController::deleteMultiple
#     methods: [POST]

# admin_prospects_send_emails:
#     path: /admin/prospects/send-emails
#     controller: App\Controller\Admin\ProspectAdminController::sendEmails
#     methods: [POST]

# admin_prospect_get_emails:
#     path: /admin/prospects/get-emails
#     controller: App\Controller\ProspectController::getEmails
#     methods: POST

# admin_prospect_delete_multiple:
#     path: /admin/prospects/delete
#     controller: App\Controller\ProspectController::deleteProspects
#     methods: [POST]


admin_prospect_delete:
    path: /admin/prospects/delete
    controller: App\Controller\Admin\ProspectAdminController::deleteProspects
    methods: [POST]


get_prospects_emails:
    path: /admin/prospects/get-emails
    controller: App\Controller\Admin\ProspectAdminController::getProspectsEmails
    methods: [POST]


install_hook_map:
    path: /admin/prospects/installHook.js.map
    controller: Symfony\Component\HttpFoundation\Response
    defaults:
        content: ''
        status: 204





# config/routes.yaml

# admin_prospect_index:
#     path: /admin/prospects/
#     controller: App\Controller\Admin\ProspectAdminController::index
#     methods: [GET]

# admin_prospect_new:
#     path: /admin/prospects/new
#     controller: App\Controller\Admin\ProspectAdminController::new
#     methods: [GET, POST]

# admin_prospect_delete_multiple:
#     path: /admin/prospects/delete-multiple
#     controller: App\Controller\Admin\ProspectAdminController::deleteMultiple
#     methods: [POST]

# admin_prospect_get_emails:
#     path: /admin/prospects/get-emails
#     controller: App\Controller\Admin\ProspectAdminController::getEmails
#     methods: [POST]

# admin_prospects_send_emails:
#     path: /admin/prospects/send-emails
#     controller: App\Controller\Admin\ProspectAdminController::sendEmails
#     methods: [POST]

# admin_prospect_get_emails:
#     path: /admin/prospects/get-emails
#     controller: App\Controller\Admin\ProspectAdminController::getEmails
#     methods: [POST]



# Routes pour les prospects
admin_prospect_index:
    path: /admin/prospects
    controller: App\Controller\Admin\ProspectAdminController::index
    methods: [GET]

# admin_prospect_new:
#     path: /admin/prospects/new
#     controller: App\Controller\Admin\ProspectAdminController::new
#     methods: [GET, POST]

admin_prospect_edit:
    path: /admin/prospects/{id}/edit
    controller: App\Controller\Admin\ProspectAdminController::edit
    methods: [GET, POST]

admin_prospect_delete_multiple:
    path: /admin/prospects/delete-multiple
    controller: App\Controller\Admin\ProspectAdminController::deleteMultiple
    methods: [POST]

admin_prospect_get_emails:
    path: /admin/prospects/get-emails
    controller: App\Controller\Admin\ProspectAdminController::getEmails
    methods: [POST]

admin_prospects_send_emails:
    path: /admin/prospects/send-emails
    controller: App\Controller\Admin\ProspectAdminController::sendEmails
    methods: [POST]

admin_prospect_delete_individual:
    path: /admin/prospects/delete
    controller: App\Controller\ProspectController::deleteIndividualProspect
    methods: [DELETE]






admin_prospect_new:
    path: /admin/prospects/new
    controller: App\Controller\Admin\ProspectAdminController::create
    methods: [GET, POST]

admin_page_visits_reset:
    path: /admin/page-visits/reset
    controller: App\Controller\Admin\PageVisitAdminController::resetVisits
    methods: [POST]


admin_page_visit_delete:
    path: /admin/page-visits/{id}
    controller: App\Controller\Admin\PageVisitAdminController::delete
    methods: [POST]








send_email:
    path: /send-email
    controller: App\Controller\EmailController::sendEmail
    methods: POST





admin_prospect_index2:
    path: /admin/prospects
    controller: App\Controller\ProspectController::pagination
    methods: [GET]


admin:
    path: /admin
    controller: App\Controller\AdminController::index

app_logout:
    path: /logout
