controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

api_record_visit:
    path: /api/visit/{pageUrl}
    controller: App\Controller\PageVisitController::recordVisit
    methods: [POST, OPTIONS]
 
api_get_visits:
    path: /api/visit
    controller: App\Controller\PageVisitController::getVisits
    methods: [GET]

api_reset_visits:
    path: /api/visit
    controller: App\Controller\PageVisitController::resetVisits
    methods: [DELETE]

# api_contact:
#     path: /api/contact
#     controller: App\Controller\ProspectController::handleContact
#     methods: ['POST']






check_ip:
    path: /api/check-ip
    controller: App\Controller\IpVerificationController::checkIp



# config/routes.yaml
dashboard:
    path: /api/dashboard/{token}
    controller: App\Controller\DashboardController::getDashboardData
    requirements:
        token: '.*'  # Capturer n'importe quelle valeur de token



# Routes pour la gestion des prospects
api_contact:
    path: /api/contact
    controller: App\Controller\ProspectController::handleContact
    methods: POST

api_devis:
    path: /api/devis
    controller: App\Controller\ProspectController::handleDevis
    methods: POST

api_prospects_list:
    path: /api/prospects
    controller: App\Controller\ProspectController::listProspects
    methods: GET

api_prospects_create:
    path: /api/prospects
    controller: App\Controller\ProspectController::createProspect
    methods: POST

api_prospect_update:
    path: /api/prospect/{id}
    controller: App\Controller\ProspectController::updateProspect
    methods: PUT

api_prospect_delete:
    path: /api/prospect/{id}
    controller: App\Controller\ProspectController::deleteProspect
    methods: DELETE

api_prospects_bulk_delete:
    path: /api/prospects/delete
    controller: App\Controller\ProspectController::deleteMultipleProspects
    methods: POST

# Routes pour la gestion des visites
api_visits:
    path: /api/visit
    controller: App\Controller\VisitController::listVisits
    methods: GET

api_visit_reset:
    path: /api/visit/reset
    controller: App\Controller\VisitController::resetVisits
    methods: DELETE



send_email:
  path: /api/send-email
  controller: App\Controller\EmailController::sendEmail
  methods: [POST]



# config/routes.yaml

api_auto_login:
  path: /api/auto-login
  controller: App\Controller\AutoLoginController::autoLogin
  methods: [GET]
